inverse1: false
inverse2: false
laser1Alpha: 0.0
laser1AngleMax: 181.0
laser1AngleMin: -181.0
laser1B: 0
laser1G: 0
laser1R: 255
laser1XOff: 0.18
laser1YOff: 0.0
laser1ZOff: 0.0
laser2Alpha: 180.0
laser2AngleMax: 181.0
laser2AngleMin: -181.0
laser2B: 255
laser2G: 0
laser2R: 0
laser2XOff: -0.15
laser2YOff: 0.0
laser2ZOff: 0.0
pointCloudTopic: cloud_in
pointCloutFrameId: laser_link
qos_overrides./parameter_events.publisher.depth: 1000
qos_overrides./parameter_events.publisher.durability: volatile
qos_overrides./parameter_events.publisher.history: keep_last
qos_overrides./parameter_events.publisher.reliability: best_effort
scanTopic1: /lidar_1/scan
scanTopic2: /lidar_2/scan
show1: true
show2: true
use_sim_time: false
